spring:
  application:
    name: Preonboarding-Backend-Course

  datasource:
    url: jdbc:mysql://localhost:3306/login
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false

jwt:
  secret:
    key: ${jwt.secret.key}

logging:
  level:
    com:
      springboot:
        preonboardingbackendcourse:
          global:
            filter:
              JwtAuthorizationFilter: DEBUG

---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    url: jdbc:h2:mem:testdb
    password: ''

  data:
    redis:
      port: 6379
      host: localhost

  application:
    name: Preonboarding-Backend-Course

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true

jwt:
  secret:
    key: 7Iqk7YyM66W07YOA7L2U65Sp7YG0657Iqk7YyM66W07YOA7L2U65Sp7YG065
